version: '3.8'

services:
  backend:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - backend_node_modules:/app/backend/node_modules
      - backend_dist:/app/backend/dist

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  backend_node_modules:
  backend_dist: 