version: '3.8'

services:
  backend:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge 